### ISSUE TITLE
Breaking Changes with Dplyr >= 0.5.0

### ISSUE THREAD

**Issue by cwbishop** [piersharding/dplyrimpaladb#10]
Hello,

Just wanted to note that dplyr 0.5.0 introduced breaking changes for this package. Will not install unless src_translate_env is changed to sql_translate_env. However, even with this change, queries are not executing properly. I tinkered with it for a bit, but couldn't put my finger on the root cause.

-Chris

**Comment by piersharding** [comment]
Hi -

looks like there a a bunch of changes that break backwards compatibility.  I'll look into this, but in the meantime you should be able to make things work with downgrading dplyr as per this:

```
pkg_url <- "https://cran.rstudio.com/src/contrib/Archive/dplyr/dplyr_0.4.3.tar.gz"
install.packages(pkg_url, repos = NULL, type = "source")
```

from https://github.com/imanuelcostigan/RSQLServer/issues/68

**Comment by cwbishop** [comment]
Hello,

I can also confirm that downgrading dplyr fixes the issue. After an hour or so of tinkering trying to fix the issue, I decided to bite the bullet and downgrade dplyr.

Thank you!

-Chris

**Comment by piersharding** [comment]
HI - good - atleast that gets you going.  I've figured out the first problem with sql_translate_env, but there are a whole lot of other issues created by other internal changes - in particular around joins.  I should have something for that in the next few days.

Cheers.

**Comment by piersharding** [comment]
Hi Chris -

I think I have this sorted.  Can you upgrade to 0.5.0 dplyr, and latest from https://github.com/piersharding/dplyrimpaladb and let me know if it works for you.

Thanks,
Piers Harding.

**Comment by cwbishop** [comment]
Hi Piers,

I installed dplyr 0.5.9 and the most recent version of dplyrimpaladb. It seems to work great!

Thank you very much for your help in getting this up and running again.

If you wouldn't mind sending me a message offline, I'd appreciate it ...

chriswbishop [at] gmail.com

-Chris

**Comment by chezou** [comment]
It seems the problem was resolved. Is there any reason to keep opening it?
