### ISSUE TITLE
Require lazy instead of lazyeval

### ISSUE THREAD

**Issue by eaurele** [piersharding/dplyrimpaladb#11]
Don't you mean to `require()` the `lazyeval` package rather than the `lazy` package here? https://github.com/piersharding/dplyrimpaladb/blob/master/R/src-impaladb.r#L239

**Comment by piersharding** [comment]
I think that  is due to a change of package name that may have happened at around dplyr 0.5.0 (https://github.com/hadley/dplyr/blob/master/DESCRIPTION#L25) - I can probably drop the require all together.

**Comment by eaurele** [comment]
Since `lazyeval` and other `require()`d packages are already listed in `DESCRIPTION` `Imports:`, I think so too :)

**Comment by piersharding** [comment]
Pushed 0.0.10
