### ISSUE TITLE
Borrow functions

### ISSUE THREAD

**Issue by wush978** [piersharding/dplyrimpaladb#2]
Dear @piersharding ,

I am developing a Spark SQL backend for dplyr via Thrift Server. Before noticing your project, I successfully makes the dplyr connect to Spark SQL Server, create table and do some simple verbs such as select, filter, and mutate. The experimental work is here: https://github.com/wush978/dplyrSparkSQL

Could I borrow some of your code to accomplish all common verbs for dplyr such as joining and group by? I will put you into the author in the DESCRIPTION if you agree.

Thanks

**Comment by piersharding** [comment]
Hi - thanks   for   asking   and it sounds   like   a   great   project .   More   than   happy   for   you   to   make   use   of   any   code   I've   written .  
Not   sure   if   you   have   seen   this   yet but   there   are   limitations   with   RJDBC where   it does   not   implement   all   the   things   that   dplyr would   expect   from   a   driver .  But   then impaladb and spark are   not   exactly   sql compliant . 

Cheers  
Piers   Harding

**Comment by wush978** [comment]
Thanks for your agreement and reminding. 

I have not explored all features yet, but I defined a customized connection S3 connection class `Hive2Connection`. Once I need to extend the JDBC driver, I could define my own S3 method for `Hive2Connection`.

**Comment by wush978** [comment]
Dear @piersharding ,

After borrowing and modifying your scripts, the `joining` and `group by` work now.

Many thanks.
