### ISSUE TITLE
Close connection

### ISSUE THREAD

**Issue by daroczig** [piersharding/dplyrimpaladb#4]
First of all, thanks for this package.

I wonder if there's a way to close the connection so that the queries "in flight" would be cleared at Impala.  What I've tried:

``` r
> dbDisconnect(flights)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘dbDisconnect’ for signature ‘"src_impaladb"’

> rm(flights)
> gc()
Error in paste(con@Id, collapse = ", ") : 
  no slot of name "Id" for this object of class "ImpalaDBConnection"
```

**Comment by daroczig** [comment]
For the record, I managed to close the connection via:

``` r
> x <- flights$con
> class(x) <- c('JDBCConnection')
> dbDisconnect(x)
[1] TRUE
```

**Comment by piersharding** [comment]
Hi - I've pushed up a fix for the finalizer, which should work correctly for you now with:

> rm(flights)
> gc()

Thanks,
Piers.

**Comment by daroczig** [comment]
Works like a charm, thank you!
