### ISSUE TITLE
testthat dependency

### ISSUE THREAD

**Issue by daroczig** [piersharding/dplyrimpaladb#5]
It [seems](https://github.com/piersharding/dplyrimpaladb/blob/master/R/src-impaladb.r#L226) that `src_impaladb` (which is the main fn in the pkg) depends on `testthat`, which is only suggested in the `DESCRIPTION` file. If it's really needed, I'd rather have it in the `Imports` field as a hard dependency -- although I am not sure why this package `require`d.

**Comment by piersharding** [comment]
Hi -
Yes, this is wrong.  I've removed the dependency  - commit https://github.com/piersharding/dplyrimpaladb/commit/6c6524462100813645076345931d0723c9c76eca .

Thanks,
Piers.

**Comment by daroczig** [comment]
Thanks a lot!
